<?php

namespace app\admin\controller;
use think\Controller;
use think\Config;
use think\Session;

class Base extends Controller{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if (!in_array($this->request->action(), array('login', 'verification','do_login'))) {
            //检查管理员登录状态
            $check = Session::get('login_admin');
            if (!empty($check)) {
                $this->assign('login_admin', $check);
            }else{
                $this->redirect(url('Index/login'));
            }
        }
    }


}